<?php
/** @var map_block_map_marker_content $this */
/** @var manage_model_event $event */
$event = $this->getVar('event');
?>
<style>
    .tab{
        height:206px;
        width:368px;
    }
</style>
<div class="marker-content">
    <h1><?php echo $event->getData('title') ?></h1>

    <div id="marker-tabs" class="tabs">

        <ul style="font-size:10px;">
            <li><a href="#tab-image">Изображение</a></li>
            <li><a href="#tab-data">Данные</a></li>
            <li><a href="#tab-tool">Управление</a></li>
        </ul>
        <div id="tab-image" class="tab">
           <a target="_blank" href="<?php echo $this->getUrl($event->getData('image')); ?>"> <img width="360px" src="<?php echo $this->getUrl($event->getData('image')); ?>"/></a>
        </div>
        <div id="tab-data" class="marker-data tab" >
            <table class="info-table" width="370px" height="206">
                <tr>
                    <td>Дата, время</td>
                    <td><?php echo date('d.m.Y H:i', $event->getData('date')) ?></td>
                </tr>
                <tr>
                    <td>Агент</td>
                    <td><?php echo $event->getData('user_fullname') ?></td>
                </tr>
                <tr>
                    <td>Город</td>
                    <td><?php echo $event->getData('city_name') ?></td>
                </tr>
                <tr>
                    <td>Активность</td>
                    <td><?php echo $event->getData('activity_name') ?></td>
                </tr>
            </table>
        </div>
        <div id="tab-tool" class="tab" >
            <button class="button-event-delete" event_id="<?php echo $event->getId() ?>" onclick="gisTrade.deleteEvent('<?php echo $event->getId() ?>')">Удалить</button>
        </div>

    </div>

</div>
