<ul>
    <li>
        <a href="<?php echo $this->getUrl('manage/city/index/') ?>">Города</a>
    </li>
    <li>
        <a href="<?php echo $this->getUrl('manage/activity/index/') ?>">Активности</a>
    </li>
    <li>
        <a href="">Люди</a>
        <ul>
            <li>
                <a href="">Администраторы</a>
            </li>
            <li>
                <a href="">Региональные руководители</a>
            </li>
            <li>
                <a href="">Торговые представители</a>
            </li>
        </ul>
    </li>
</ul>