<?php
$filter = $this->getVar('filter');
/** @var core_model_user $luser */
$luser = app::getSession()->getLoggedInUser();
?>
<style>
    #controls {
        position: absolute;
        top: 35px;
        left: 20px;
        z-index: 99;
        /*background-color: #fff;*/
        padding: 10px;
        height: 300px;
        width: 350px;
        /*opacity: 0.8;*/
        /*border:1px solid #ccc;*/
        display: none;
    }
    a.tree_expand_ctrl{
     text-decoration: none;
        font-weight:bold;
    }

</style>
<div id="controls">

    <div id="controls-tabs" class="tabs">

        <ul style="font-size:10px;">
            <li><a href="#tab-date">Период</a></li>
            <li><a href="#tab-managers">Персонал</a></li>
            <li><a href="#tab-activity">Активности</a></li>
            <!--li><a href="#tab-city">ГЕО</a></li-->
            <!--li><a href="#tab-traders">Агенты (времмено)</a></li-->

            <li>
                <a href="#tab-settings" title="Настройки">
                    <img height="10px" src="<?php echo $this->getSkinUrl('img/user_info.png') ?>"/>
                </a>
            </li>
        </ul>
        <form id="controls-form" method="post">
            <div id="tab-date">
                <p>От: <input type="text" name="filter[date][from]"
                              value="<?php echo date('d.m.Y', $filter['date']['from']) ?>" class="datepicker"></p>

                <p>До: <input type="text" name="filter[date][to]"
                              value="<?php echo date('d.m.Y', $filter['date']['to']) ?>" class="datepicker"></p>

                <div class="ui-buttonset">
                    <button class="button" onclick="$('#controls-form').submit()"><span>Применить</span></button>
                </div>
            </div>
            <div id="tab-activity">
                <a href="javascript:void(0);" class="check-all-filters"
                   selector="input.marker-field-filter[field=activity_id]">Отметить все</a>
                &nbsp;|&nbsp;
                <a href="javascript:void(0);" class="uncheck-all-filters"
                   selector="input.marker-field-filter[field=activity_id]">Снять отметку</a>

                <div style="max-height:600px;overflow-y:auto;">
                    <table>
                        <?php foreach ($this->getVar('activities') as $activity): ?>
                            <tr>
                                <td>
                                    <input type="checkbox" checked field="activity_id"
                                           field_value="<?php echo $activity->getId() ?>" class="marker-field-filter"
                                           name="filter[activity][<?php echo $activity->getId() ?>]"
                                           id="activity_<?php echo $activity->getId() ?>"
                                        />
                                </td>
                                <td>
                                    <label
                                        for="activity_<?php echo $activity->getId() ?>"><?php echo $activity->getData('name') ?></label>
                                </td>

                            </tr>
                        <?php endforeach ?>
                    </table>
                </div>
            </div>
            <!--div id="tab-city">
                <a href="javascript:void(0);" class="check-all-filters"
                   selector="input.marker-field-filter[field=city_id]">Отметить все</a>
                &nbsp;|&nbsp;
                <a href="javascript:void(0);" class="uncheck-all-filters"
                   selector="input.marker-field-filter[field=city_id]">Снять отметку</a>


                <div style="max-height:600px;overflow-y:auto;">
                    <table>

                        <?php foreach ($this->getVar('cities') as $city): ?>
                            <tr>
                                <td>
                                    <input type="checkbox" checked field="city_id"
                                           field_value="<?php echo $city->getId() ?>" class="marker-field-filter"
                                           name="filter[city][<?php echo $city->getId() ?>]"
                                           id="city_<?php echo $city->getId() ?>"/>
                                </td>
                                <td>
                                    <label
                                        for="city_<?php echo $city->getId() ?>"><?php echo $city->getData('name') ?></label>
                                </td>

                            </tr>
                        <?php endforeach ?>
                    </table>
                </div>
            </div-->
            <!--div id="tab-traders">
                <a href="javascript:void(0);" class="check-all-filters"
                   selector="input.marker-field-filter[field=user_id]">Отметить все</a>
                &nbsp;|&nbsp;
                <a href="javascript:void(0);" class="uncheck-all-filters"
                   selector="input.marker-field-filter[field=user_id]">Снять отметку</a>

                <div style="max-height:600px;overflow-y:auto;">
                    <table>

                        <?php

                        foreach ($this->getVar('traders') as $trader): ?>
                            <?php
                            $hc = '';
                            $checked = 'checked';
                            if ($luser->getData('role_id') != manage_model_role::ROLE_ADMIN):?>
                                <?php if ($trader->getData('parent_id') != $luser->getId()):
                                    $hc = 'hidden';
                                    $checked = '';
                                endif; ?>
                            <?php endif ?>

                            <tr class="<?php echo $hc; ?>" parent_id="<?php echo $trader->getData('parent_id') ?>">
                                <td>

                                    <input

                                        <?php echo $checked ?>
                                        type="checkbox" trader_id="<?php echo $trader->getId() ?>"
                                        field="user_id" field_value="<?php echo $trader->getId() ?>"
                                        class="marker-field-filter "
                                        name="filter[trader][<?php echo $trader->getId() ?>]"
                                        id="user_<?php echo $trader->getId() ?>"
                                        />
                                </td>
                                <td>
                                    <?php
                                    $manager = new manage_model_user();
                                    $manager->load($trader->getData('parent_id'));
                                    ?>
                                    <label for="user_<?php echo $trader->getId() ?>"
                                           title="Менеджер: <?php echo $manager->getData('fullname'); ?>">
                                        <?php echo $trader->getData('fullname') ?>
                                    </label>

                                </td>

                            </tr>
                        <?php endforeach ?>
                    </table>
                </div>
            </div-->
            <div id="tab-managers">
                <!--a href="javascript:void(0);" class="check-all-filters"
                   selector="input.marker-field-filter[field=user_id]">Отметить все</a>
                &nbsp;|&nbsp;
                <a href="javascript:void(0);" class="uncheck-all-filters"
                   selector="input.marker-field-filter[field=user_id]">Снять отметку</a-->

                <div style="max-height:600px;overflow-y:auto;">
                    <table width="98%">

                        <?php

                        foreach ($this->getVar('cities') as $city):
                            $managers = $city->getManagerCollection();
                            $managers->load();
                            if(!$managers->count()){
                                continue;
                            }
                            ?>
                            <tr>
                                <td valign="top" width="2%">
                                    <input class="depend-children" depend="#tree_city_<?php echo $city->getId() ?>_content input[type=checkbox]" type="checkbox" checked  id="tree_city_<?php echo $city->getId() ?>"/>
                                </td>
                                <td valign="top">
                                    <a href="javascript:void(0);" class="tree_expand_ctrl" for="tree_city_<?php echo $city->getId() ?>_content" id="tree_city_<?php echo $city->getId() ?>_expand_ctrl">
                                        <i>+</i><?php echo $city->getData('name') ?>
                                    </a>
                                    <div id="tree_city_<?php echo $city->getId() ?>_content" style="display: none;">
                                        <table width="100%" cellspacing="0">
                                            <?php foreach( $managers as $manager ): ?>
                                                <tr>
                                                    <td valign="top" width="2%" style="border-left:1px dotted silver;">
                                                        <input type="checkbox" class="depend-children" depend="#tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>_content input[type=checkbox]" checked id="tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>"/>
                                                    </td>
                                                    <td valign="top" >
                                                        <a href="javascript:void(0);" class="tree_expand_ctrl" for="tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>_content" >-</a>
                                                        <label for="tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>" style="font-weight:bold;">
                                                            <?php echo $manager->getData('fullname') ?>
                                                        </label>
                                                        <div id="tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>_content">
                                                            <table width="100%" cellspacing="0">
                                                            <?php foreach($manager->getManagerChildrenCollection() as $trader):?>
                                                                <tr>
                                                                    <td width="2%" style="border-left:1px dotted silver; ">
                                                                        <input
                                                                            checked
                                                                            type="checkbox" trader_id="<?php echo $trader->getId() ?>"
                                                                            field="user_id" field_value="<?php echo $trader->getId() ?>"
                                                                            class="marker-field-filter "
                                                                            name="filter[trader][<?php echo $trader->getId() ?>]"
                                                                            id="user_<?php echo $trader->getId() ?>"
                                                                            />
                                                                    </td>
                                                                    <td>
                                                                        <label for="user_<?php echo $trader->getId() ?>" >
                                                                            <img height="12px" src="http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|<?php echo $trader->getData('marker_color') ? str_replace('#','',$trader->getData('marker_color')) : '#000' ?>" />
                                                                            <?php echo $trader->getData('fullname') ?>
                                                                            (<span ___style="color: <?php echo $trader->getData('marker_color') ? $trader->getData('marker_color') : '#000' ?>" title="Количество событий"><?php echo $trader->getEventsCount($filter['date']['from'],$filter['date']['to']) ?></span>)
                                                                        </label>
                                                                    </td>
                                                                </tr>
                                                            <?php endforeach;?>
                                                            </table>
                                                        </div>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </table>
                                    </div>
                                </td>
                            </tr>


                        <?php endforeach ?>

                        <?php

                            $city = new manage_model_city();
                            $city->setId(NULL);
                            $managers = $city->getManagerCollection();
                            $managers->load();

                            ?>
                            <tr>
                                <td valign="top" width="2%">
                                    <input type="checkbox" class="depend-children" depend="#tree_city_<?php echo $city->getId() ?>_content input[type=checkbox]" checked id="tree_city_<?php echo $city->getId() ?>"/>
                                </td>
                                <td valign="top">
                                    <a href="javascript:void(0);" class="tree_expand_ctrl" for="tree_city_<?php echo $city->getId() ?>_content" id="tree_city_<?php echo $city->getId() ?>_expand_ctrl">
                                        <i>+</i>Супервайзеры без привязки
                                    </a>
                                    <div id="tree_city_<?php echo $city->getId() ?>_content" style="display: none;">
                                        <table width="100%" cellspacing="0">
                                            <?php foreach( $managers as $manager ): ?>
                                                <tr>
                                                    <td valign="top" width="2%" style="border-left:1px solid silver;">
                                                        <input type="checkbox" class="depend-children" depend="#tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>_content input[type=checkbox]" checked id="tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>"/>

                                                    </td>
                                                    <td valign="top">
                                                        <a href="javascript:void(0);" class="tree_expand_ctrl" for="tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>_content" >-</a>
                                                        <label for="tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>" style="font-weight:bold;">
                                                            <?php echo $manager->getData('fullname') ?>
                                                        </label>
                                                        <div id="tree_city_<?php echo $city->getId() ?>_manager_<?php echo $manager->getId() ?>_content">
                                                            <table width="100%" cellspacing="0">
                                                                <?php foreach($manager->getManagerChildrenCollection() as $trader):?>
                                                                    <tr>
                                                                        <td width="2%" style="border-left:1px solid silver;">
                                                                            <input
                                                                                checked
                                                                                type="checkbox" trader_id="<?php echo $trader->getId() ?>"
                                                                                field="user_id" field_value="<?php echo $trader->getId() ?>"
                                                                                class="marker-field-filter "
                                                                                name="filter[trader][<?php echo $trader->getId() ?>]"
                                                                                id="user_<?php echo $trader->getId() ?>"
                                                                                />
                                                                        </td>
                                                                        <td>
                                                                            <label for="user_<?php echo $trader->getId() ?>" style="color:#ee3333">
                                                                                <?php echo $trader->getData('fullname') ?>
                                                                                <span title="Количество событий">(<?php echo $trader->getEventsCount($filter['date']['from'],$filter['date']['to']) ?>)</span>
                                                                            </label>
                                                                        </td>
                                                                    </tr>
                                                                <?php endforeach;?>
                                                            </table>
                                                        </div>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </table>
                                    </div>
                                </td>
                            </tr>
                        <?php

                        $user = new manage_model_user();
                        $traders = $user->getWoParentCollection();
                        ?>
                        <tr>
                            <td valign="top" width="2%">
                                <input type="checkbox" class="depend-children" depend="#tree_city_<?php echo 'wo' ?>_content input[type=checkbox]" checked id="tree_city_<?php echo 'wo' ?>"/>
                            </td>
                            <td valign="top">
                                <a href="javascript:void(0);" class="tree_expand_ctrl" for="tree_city_<?php echo 'wo' ?>_content" id="tree_city_<?php echo 'wo' ?>_expand_ctrl">
                                    <i>+</i>Агенты без привязки
                                </a>

                                    <div id="tree_city_<?php echo 'wo' ?>_content">
                                        <table width="100%" cellspacing="0">
                                            <?php foreach($traders as $trader):?>
                                                <tr>
                                                    <td width="2%" style="border-left:1px solid silver;">
                                                        <input
                                                            checked
                                                            type="checkbox" trader_id="<?php echo $trader->getId() ?>"
                                                            field="user_id" field_value="<?php echo $trader->getId() ?>"
                                                            class="marker-field-filter "
                                                            name="filter[trader][<?php echo $trader->getId() ?>]"
                                                            id="user_<?php echo $trader->getId() ?>"
                                                            />
                                                    </td>
                                                    <td>
                                                        <label for="user_<?php echo $trader->getId() ?>" style="color:#ee3333">
                                                            <?php echo $trader->getData('fullname') ?>
                                                            <span title="Количество событий">(<?php echo $trader->getEventsCount($filter['date']['from'],$filter['date']['to']) ?>)</span>
                                                        </label>
                                                    </td>
                                                </tr>
                                            <?php endforeach;?>
                                        </table>
                                    </div>
                            </td>
                        </tr>


                    </table>
                </div>
            </div>

        </form>
        <div id="tab-settings">
            <form id="user_info_form" onsubmit="return false">

                <input type="hidden" name="user[user_id]" value="<?php echo $luser->getId() ?>"/>
                <table>
                    <tr>
                        <td>Имя</td>
                        <td><input type="text" name="user[fullname]" value="<?php echo $luser->getData('fullname') ?>">
                        </td>
                    </tr>
                    <tr>
                        <td>Телефон</td>
                        <td><input type="text" name="user[phone]" value="<?php echo $luser->getData('phone') ?>"></td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td><input type="text" name="user[username]" value="<?php echo $luser->getData('username') ?>">
                        </td>
                    </tr>
                    <tr>
                        <td>Пароль</td>
                        <td>
                            <a href="javascript:void(0);" onclick="$('#user_change_password').fadeToggle()">Изменить
                                пароль</a>
                            <table id="user_change_password" style="display:none">
                                <tr>
                                    <td>Новый пароль</td>
                                    <td><input type="password" name="user[password]"></td>
                                </tr>
                                <tr>
                                    <td>Еще раз</td>
                                    <td><input type="password" name="user[password_repeat]"></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                <button class="ui-button">Сохранить</button>

            </form>
        </div>
    </div>


</div>
<!--div id="version">
    Версия обновлена.
    <br/>
    <br/>
    Возможна нестабильная работа приложения.
    <br/>
    <br/>

    <br/>
    1. Привяжите Менеджера (супервайзера) к городу.
    <br/>
    2. Привяжите агента к менеджеру.
    <br/>
    3. см. Фильтры "Менеджеры без привязки"
    <br/>
    4. см. Фильтры "Агенты без привязки"
    <br/>
    <br/>
    xx: Менеджеры времмено имеют доступ ко всем фильтрам. (к обсуждению - нужен ли вообще такой вид доступа)

    <!--a target="_blank" href="<?php echo $this->getUrl('manage/feedback/report') ?>">С ошибками/предложениями сюда</a-->
</div-->

<style>
    #manage-toolbar {
        position: absolute;
        top: 0px;
        left: 45%;
        background-color: #fff;
        z-index: 99;
        padding: 5px;
        border-bottom-left-radius: 4px;
        border-bottom-right-radius: 4px;
        border: 1px solid #ccc;
        opacity: 0.8;
    }

    #manage-dialog {
        display: none;
    }
</style>
<div id="manage-toolbar">
    <?php //if ($luser->getData('role_id') == manage_model_role::ROLE_ADMIN) : ?>
        <a target="_blank" href="<?php echo $this->getUrl('manage/index/index') ?>" _id="manage" >Администрирование</a>
    <?php //endif; ?>
    &nbsp;|&nbsp;
    <a style="color:red" href="javascript:void(0)" id="toolbar-button-report-issue">Сообщить о проблеме</a>
    &nbsp;|&nbsp;
    <a href="<?php echo $this->getUrl('map/index/logout') ?>">Выход</a>

</div>
<div id="manage-dialog">
    <div id="manage-dialog-content">
        content
    </div>
</div>
<script>
    $(function () {
        $('#version').dialog({
            modal: true,
            width:400,
            buttons:[{

                text: 'Закрыть',
                click: function () {
                    $(this).dialog('close');
                }
            }
            ]
        });
        $('#controls').show();//.draggable();

        progressBar = '<img src="<?php echo self::getSkinUrl("images/progress-bar.gif", 'manage') ?>"/>';
        $('#manage').click(function () {
            $('#manage-dialog-content').html(progressBar);
            $('#manage-dialog').dialog({
                title: 'Управление',
                modal: true,
                width: 950,
                height: 600,
                buttons: [
                    {
                        text: "Закрыть",
                        click: function () {
                            location.href = location.href;
                            $(this).dialog("close");
                        }
                    }
                ]
            });
            $("#manage-dialog .ui-dialog-titlebar").hide();
            $.ajax({
                url: "<?php echo $this->getUrl('manage/index/ajaxindex') ?> ",
                dataType: 'text',
                complete: function (response) {
                    $('#manage-dialog-content').html(response.responseText);

                }
            })
        });

        $('#user_info_form').on('submit', function () {
            $.ajax({
                url: '<?php echo $this->getUrl('manage/user/save') ?>',
                type: 'POST',
                data: $('#user_info_form').serialize(),
                complete: function (response) {
                    if (response.responseText) {
                        $('#manage-dialog-content').html(response.responseText);
                        $('#manage-dialog').dialog({
                            title: 'Управление',
                            modal: true,
                            width: 300,
                            height: 200,
                            buttons: [
                                {
                                    text: "Закрыть",
                                    click: function () {
                                        $(this).dialog("close");
                                    }
                                }
                            ]
                        });

                    }
                    else {
                        alert('OK');
                    }
                }
            });
        })

        $('input.marker-field-filter').on('click', function () {
            gisTrade.filterMarkers();
        });

        $('.check-all-filters').on('click', function () {
            $($(this).attr('selector')).prop('checked', true);
            gisTrade.filterMarkers();
        });
        $('.uncheck-all-filters').on('click', function () {
            $($(this).attr('selector')).prop('checked', false);
            gisTrade.filterMarkers();
        });

        $('.tree_expand_ctrl').on('click', function(){
            $('#'+$(this).attr('for')).toggle();
            $(this).find('i').html( $(this).find('i').html()=='+' ? '-' : '+' );
        });

        $('.depend-children').click(function(){
            $($(this).attr('depend')).prop('checked', $(this).prop('checked') );
            gisTrade.filterMarkers();
        });

    });
</script>
<!--
-->
<div id="flowze-report-isue" class="hidden">
    <div style="color:red"><?php echo $this->l('In progress') ?></div>
    0977454582
</div>
<script>
    $('#toolbar-button-report-issue').click(function(){
        $('#flowze-report-isue').dialog({
            modal: true,
            title: '<?php echo $this->l('Сообщить о проблеме') ?>',
            buttons: [{
                text: '<?php echo $this->l('Закрыть') ?>',
                click: function () {
                    $(this).dialog('close');
                }
            }]
        });
    });
</script>
<!--
-->
