<?php /** @var manage_block_activity_grid $this*/?>
<?php
$collection = $this->getVar('collection');
$collection->load();
?>

<table id="activity-grid" cellspacing="0" cellpadding="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Активность</th>
            <!--th>К-во событий</th-->
            <th></th>
        </tr>
    </thead>
<?php foreach($this->getVar('collection') as $activity): ?>
    <tr activity_id="<?php echo $activity->getId()?>">
        <td><?php echo $activity->getId()?></td>
        <td><?php echo $activity->getData('name')?></td>
        <!--td><?php echo $activity->getData('events_sum')?></td-->
        <td>
            <ul id="icons" class="ui-widget ui-helper-clearfix right">
                <li onclick="activityManager.getForm(<?php echo $activity->getId()?>)" class="ui-state-default ui-corner-all" title="Изменить"><span class="ui-icon ui-icon-pencil"></span></li>
                <li onclick="activityManager.deleteactivity(<?php echo $activity->getId()?>)" activity_id="<?php echo $activity->getId()?>" class="activity-grid-delete ui-state-default ui-corner-all" title="Удалить"><span class="ui-icon ui-icon-trash"></span></li>
             </ul>
        </td>
    </tr>
<?php endforeach?>
</table>
